basic:
  use_compressed_image: true
  use_lidar: true
  enable_pcp_vis: true
  lidar_topic: /rslidar_points
  camera_topic: /camera2/color/image_raw/compressed
  map_frame: map
  lidar_frame: rslidar
  camera_frame: camera2_link

tracker:
  track_fail_timeout_tick: 30
  bbox_overlap_ratio: 0.6
  detector_update_timeout_tick: 30
  detector_bbox_padding: 80
  reid_match_threshold: 3.0
  reid_match_bbox_dis: 80
  reid_match_bbox_size_diff: 80
  stop_opt_timeout: 6

local_database:
  height_width_ratio_min: 0.85
  height_width_ratio_max: 4.0
  blur_detection_threshold: 20.0
  record_interval: 0.1
  batch_num_min: 8
  feature_smooth_ratio: 0.7

pc_processor:
  resample_size: 0.1
  x_min: 0.0
  x_max: 15.0
  z_min: 0.0
  z_max: 4.04
  std_dev_thres: 0.1
  mean_k: 20
  cluster_tolerance: 0.5
  cluster_size_min: 20
  cluster_size_max: 10000
  match_centroid_padding: 20

camera_intrinsic:
  fx: 613.783
  fy: 612.895
  cx: 416.969
  cy: 240.223

kalman_filter:
  q_xy: 100
  q_wh: 25
  p_xy_pos: 100
  p_xy_dp: 10000
  p_wh_size: 25
  p_wh_ds: 25
  r_theta: 0.08 # 0.02 rad 1 degree
  r_f: 0.04
  r_tx: 4
  r_ty: 4
  residual_threshold: 16

kalman_filter_3d:
  q_factor: 100 # 2m/s max speed, 0.5m/s uncertainty
  r_factor: 0.25 # 1m
  p_pos: 100
  p_vel: 4
  start_predict_only_timeout: 10
  stop_track_timeout: 15
  outlier_threshold: 4.0

optical_flow:
  min_keypoints_to_track: 40
  keypoints_num_factor_area: 8000
  corner_detector_max_num: 100
  corner_detector_quality_level: 0.0001
  corner_detector_min_distance: 3
  corner_detector_block_size: 3
  corner_detector_use_harris: true
  corner_detector_k: 0.03
  min_keypoints_to_cal_H_mat: 10
  min_keypoints_for_motion_estimation: 50
  min_pixel_dis_square_for_scene_point: 2
  use_resize: true
  resize_factor: 2
