data_topic:
  lidar_topic: /livox/lidar
  camera_topic: /camera/color/image_raw/compressed
  depth_topic: /livox/lidar

tracker:
  track_fail_timeout_tick: 3
  bbox_overlap_ratio: 0.5
  track_to_reid_bbox_margin: 0
