data_topic:
  lidar_topic: /livox/lidar
  camera_topic: /camera/color/image_raw/compressed
  depth_topic: /livox/lidar

tracker:
  track_fail_timeout_tick: 1
  bbox_overlap_ratio: 0.4

local_database:
  height_width_ratio_min: 1.0
  height_width_ratio_max: 3.0
  blur_detection_threshold: 200.0
  record_interval: 0.1
  batch_num_min: 3
